"""
File: sync_requirements.py
Description: Keeps the root Pipfile's [packages] section in step with the
             requirements files of the sub-projects it has to run.

`network-design-bss/src/` is frozen: none of its .py files may change, so the
root environment has to satisfy it rather than the other way round. Its
dependency list lives in `network-design-bss/src/requirements.txt` -- the one
file inside that tree we do own -- and this script copies it up into the
Pipfile so the two can never drift apart.

    python network-design-bss/sdk-builder/sync_requirements.py            # rewrite [packages]
    python network-design-bss/sdk-builder/sync_requirements.py --check    # exit 1 if out of date

--check is what to run in CI or a pre-commit hook: it prints the lines that
differ and changes nothing.

Only [packages] is touched. [[source]], [dev-packages] and [requires] are left
exactly as they are: dev tooling (Jupyter, nbconvert) belongs to this
repository, not to the sub-project.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PIPFILE = ROOT / "Pipfile"

# Sub-projects whose dependencies the root environment must provide, in the
# order their entries should appear. Add a line here to take on another child.
CHILDREN = ("network-design-bss/src/requirements.txt",)

_MARKER = (
    "# Generated by network-design-bss/sdk-builder/sync_requirements.py -- do not edit this section by hand.\n"
    "# Source: " + ", ".join(CHILDREN) + "\n"
)

# name[extra1,extra2] <specifier> ; <environment marker>
_REQUIREMENT = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)"
    r"(?P<extras>\[[^\]]*\])?"
    r"(?P<specifier>[^;]*)"
    r"(?:;(?P<marker>.*))?$"
)


def parse_requirements(path):
    """Read a requirements.txt into ordered (name, pipfile_value) pairs.

    Comment lines are dropped, including the commented-out optional entries the
    frozen package uses to document extras it does not need at runtime. A
    requirement with no version specifier becomes pipenv's "*".

    :param path: the requirements file to read.
    :return: list of (distribution name, Pipfile TOML value string).
    :raises ValueError: if a line cannot be parsed as a requirement.
    """
    entries = []
    for lineno, raw in enumerate(path.read_text().splitlines(), start=1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("-"):
            # -r / -e / --index-url have no Pipfile [packages] equivalent.
            raise ValueError(f"{path}:{lineno}: pip option not supported here: {line}")

        match = _REQUIREMENT.match(line)
        if not match:
            raise ValueError(f"{path}:{lineno}: cannot parse requirement: {line}")

        name = match.group("name")
        specifier = (match.group("specifier") or "").strip() or "*"
        extras = match.group("extras")
        marker = (match.group("marker") or "").strip()

        if extras or marker:
            # Pipenv needs the inline-table form once there is more than a
            # version to express.
            parts = []
            if extras:
                names = ", ".join(f'"{e.strip()}"' for e in extras[1:-1].split(",") if e.strip())
                parts.append(f"extras = [{names}]")
            parts.append(f'version = "{specifier}"')
            if marker:
                parts.append(f'markers = "{marker}"')
            value = "{" + ", ".join(parts) + "}"
        else:
            value = f'"{specifier}"'

        entries.append((name, value))
    return entries


def collect():
    """Gather every child's requirements, first occurrence wins.

    :return: list of (name, value) pairs for the [packages] section.
    :raises ValueError: if two children ask for the same package differently.
    """
    seen = {}
    ordered = []
    for relative in CHILDREN:
        path = ROOT / relative
        if not path.is_file():
            raise FileNotFoundError(f"Declared child requirements not found: {path}")
        for name, value in parse_requirements(path):
            key = name.lower().replace("_", "-")
            if key in seen:
                if seen[key][1] != value:
                    raise ValueError(
                        f"{relative} wants {name} {value}, but "
                        f"{seen[key][0]} already required {value}; resolve by hand.")
                continue
            seen[key] = (relative, value)
            ordered.append((name, value))
    return ordered


def render_section(entries):
    """Build the full [packages] block, marker comment included.

    :param entries: (name, value) pairs from collect().
    :return: the section as text, ending in a blank line.
    """
    body = "".join(f"{name} = {value}\n" for name, value in entries)
    return "[packages]\n" + _MARKER + body + "\n"


def replace_section(pipfile_text, section):
    """Swap the [packages] block of a Pipfile for a freshly rendered one.

    :param pipfile_text: the current Pipfile contents.
    :param section: the replacement block from render_section().
    :return: the updated Pipfile contents.
    :raises ValueError: if the Pipfile has no [packages] section.
    """
    lines = pipfile_text.splitlines(keepends=True)
    start = next((i for i, l in enumerate(lines) if l.strip() == "[packages]"), None)
    if start is None:
        raise ValueError(f"{PIPFILE} has no [packages] section to sync.")

    end = len(lines)
    for i in range(start + 1, len(lines)):
        if lines[i].lstrip().startswith("["):
            end = i
            break

    return "".join(lines[:start]) + section + "".join(lines[end:])


def main(argv):
    check_only = "--check" in argv[1:]

    entries = collect()
    current = PIPFILE.read_text()
    updated = replace_section(current, render_section(entries))

    if current == updated:
        print(f"Pipfile [packages] is in sync with {', '.join(CHILDREN)} "
              f"({len(entries)} packages).")
        return 0

    if check_only:
        import difflib
        diff = difflib.unified_diff(
            current.splitlines(keepends=True), updated.splitlines(keepends=True),
            fromfile="Pipfile (current)", tofile="Pipfile (expected)")
        sys.stdout.writelines(diff)
        print("\nPipfile is out of date. Run: "
              "python network-design-bss/sdk-builder/sync_requirements.py")
        return 1

    PIPFILE.write_text(updated)
    print(f"Rewrote {PIPFILE} [packages] with {len(entries)} packages from "
          f"{', '.join(CHILDREN)}.")
    print("Run `pipenv lock` (or `pipenv install --dev`) to refresh Pipfile.lock.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
